### ISSUE TITLE
Identify related content

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gages-through-ages#8]
List what the related content for this viz should be. This can be other vizzies, blogs, or products. Then add to the footer.

**Comment by eread-usgs** [comment]
I propose the two related content items to be 1) Hurricane Mathew Viz and 2) Blog on dataRetrieval NWIS Stats Service - presuming we actually used that service to make this viz. @wdwatkins can you confirm if we did or did not?

**Comment by wdwatkins** [comment]
@eread-usgs No I don't think we are, unless we do for the individual site plot(s) below the main map.  We are using dataRetrieval though, so it wouldn't be totally unrelated.

**Comment by eread-usgs** [comment]
ok, thx @wdwatkins . @mwernimont Im going to pass this off to  you now since you're handling footer. Please add   1) Hurricane Mathew Viz (https://owi.usgs.gov/vizlab/hurricane-matthew/) and 2) Blog on dataRetrieval NWIS Stats Service (https://owi.usgs.gov/blog/stats-service-map/) as the two 'related content' at the bottom of the footer.
